"""Shared visual-effect geometry and painting primitives."""

from krok_helper.subtitle_render.engine.render.effects.metrics import (
    glow_blur_radii,
    glow_concentration_level,
    glow_extent,
    glow_pen_width,
    glow_radius,
    main_stroke2_width,
    ruby_baseline_y,
    ruby_decoration_kind,
    ruby_glow_concentration_level,
    ruby_glow_radius,
    ruby_paint_style,
    ruby_shadow_dx,
    ruby_shadow_dy,
    ruby_stroke_extent,
    ruby_vertical_extra,
    ruby_visual_padding,
    scaled_glow_radius,
    stroke2_pen_width,
    stroke_pen_width,
    text_visual_padding,
    title_visual_padding,
    visual_stroke_extent,
    visual_text_padding,
)


__all__ = [
    "glow_blur_radii",
    "glow_concentration_level",
    "glow_extent",
    "glow_pen_width",
    "glow_radius",
    "main_stroke2_width",
    "ruby_baseline_y",
    "ruby_decoration_kind",
    "ruby_glow_concentration_level",
    "ruby_glow_radius",
    "ruby_paint_style",
    "ruby_shadow_dx",
    "ruby_shadow_dy",
    "ruby_stroke_extent",
    "ruby_vertical_extra",
    "ruby_visual_padding",
    "scaled_glow_radius",
    "stroke2_pen_width",
    "stroke_pen_width",
    "text_visual_padding",
    "title_visual_padding",
    "visual_stroke_extent",
    "visual_text_padding",
]
