"""Ruby annotation selection, styling, timing and layout contracts."""

from krok_helper.subtitle_render.engine.ruby.selection import (
    active_rubies_for_line,
    effective_ruby_for_target,
    find_ruby_text_indices,
    find_ruby_text_span,
    ruby_explicit_target_indices,
    ruby_has_global_position,
    ruby_owns_line,
    ruby_target_indices,
    ruby_target_x_range,
    ruby_text_span_x_range,
    ruby_time_indices,
    text_span_indices,
    timed_ruby_matches_line,
)
from krok_helper.subtitle_render.engine.ruby.style import (
    build_ruby_font,
    build_ruby_font_for_text,
    ruby_font_size,
    ruby_scale,
    ruby_script_stroke_style,
    ruby_stroke2_enabled,
    ruby_stroke2_width,
    ruby_stroke2_width_value,
    ruby_stroke_width,
    ruby_style_for_target_indices,
    ruby_uses_main_font,
    scaled_px,
    scaled_signed_px,
)


__all__ = [
    "active_rubies_for_line",
    "build_ruby_font",
    "build_ruby_font_for_text",
    "effective_ruby_for_target",
    "find_ruby_text_indices",
    "find_ruby_text_span",
    "ruby_explicit_target_indices",
    "ruby_font_size",
    "ruby_has_global_position",
    "ruby_owns_line",
    "ruby_scale",
    "ruby_script_stroke_style",
    "ruby_stroke2_enabled",
    "ruby_stroke2_width",
    "ruby_stroke2_width_value",
    "ruby_stroke_width",
    "ruby_style_for_target_indices",
    "ruby_target_indices",
    "ruby_target_x_range",
    "ruby_text_span_x_range",
    "ruby_time_indices",
    "ruby_uses_main_font",
    "scaled_px",
    "scaled_signed_px",
    "text_span_indices",
    "timed_ruby_matches_line",
]
