"""Qt text measurement and immutable glyph-layout contracts."""

from krok_helper.subtitle_render.engine.text.layout import (
    GlyphLayout,
    TextLayout,
    build_role_text_layout,
    build_text_layout,
    char_left_positions,
    main_script_stroke_style,
    role_char_geometry_by_index,
    style_for_role_in_layout,
)
from krok_helper.subtitle_render.engine.text.metrics import (
    FontSelector,
    build_font,
    build_latin_font,
    char_advance,
    char_layout_width,
    char_path_left_offset,
    clamp_weight,
    clear_char_metric_cache,
    is_emoji_text,
    is_n3_latin_text,
    latin_font_size,
    latin_font_weight,
    letter_spacing,
    line_text_width,
    make_font_for,
    n3_char_box_ascent,
    n3_char_box_descent,
    nicokara_char_geometry_left_offset,
    nicokara_layout_width,
    truncate_div,
)


__all__ = [
    "FontSelector",
    "GlyphLayout",
    "TextLayout",
    "build_font",
    "build_latin_font",
    "build_role_text_layout",
    "build_text_layout",
    "char_advance",
    "char_layout_width",
    "char_left_positions",
    "char_path_left_offset",
    "clamp_weight",
    "clear_char_metric_cache",
    "is_emoji_text",
    "is_n3_latin_text",
    "latin_font_size",
    "latin_font_weight",
    "letter_spacing",
    "line_text_width",
    "main_script_stroke_style",
    "make_font_for",
    "n3_char_box_ascent",
    "n3_char_box_descent",
    "nicokara_char_geometry_left_offset",
    "nicokara_layout_width",
    "role_char_geometry_by_index",
    "style_for_role_in_layout",
    "truncate_div",
]
