"""Horizontal subtitle layout and rendering contracts."""

from krok_helper.subtitle_render.engine.render.elements.horizontal.contracts import (
    FillSegment,
    LineCharTransition,
    LineLayout,
    RubyLayout,
    RubyWipeSegment,
    SayatooLineLayout,
)
from krok_helper.subtitle_render.engine.render.elements.horizontal.positioning import (
    aligned_x0,
    bottom_short_page_alignment,
    lane_alignment,
    layout_page_lines,
    line_total_width,
    line_lane_alignment,
    n3_smart_font_size,
    resolve_line_x,
    resolve_line_x_smart,
    row_layout_params,
    smart_horizontal_dx,
)
from krok_helper.subtitle_render.engine.render.elements.horizontal.layout import (
    bitmap_guide_glyphs,
    bitmap_guide_anchor_descent,
    bitmap_guide_is_no_wipe,
    clamp_role_baseline_y,
    glyph_is_bitmap_guide,
    glyph_path,
    glyph_run_path,
    glyph_run_rect,
    glyph_run_signature,
    glyph_runs,
    fixed_line_geometry,
    n3_main_fill_rect,
    resolve_role_baseline_y,
    resolve_baseline_y,
    resolve_display_baselines,
    role_visual_text_padding,
    text_glyph_runs,
)


__all__ = [
    "FillSegment",
    "LineCharTransition",
    "LineLayout",
    "RubyLayout",
    "RubyWipeSegment",
    "SayatooLineLayout",
    "aligned_x0",
    "bitmap_guide_glyphs",
    "bitmap_guide_anchor_descent",
    "bitmap_guide_is_no_wipe",
    "bottom_short_page_alignment",
    "clamp_role_baseline_y",
    "glyph_is_bitmap_guide",
    "glyph_path",
    "glyph_run_path",
    "glyph_run_rect",
    "glyph_run_signature",
    "glyph_runs",
    "fixed_line_geometry",
    "lane_alignment",
    "layout_page_lines",
    "line_total_width",
    "line_lane_alignment",
    "n3_smart_font_size",
    "n3_main_fill_rect",
    "resolve_line_x",
    "resolve_line_x_smart",
    "resolve_role_baseline_y",
    "resolve_baseline_y",
    "resolve_display_baselines",
    "role_visual_text_padding",
    "row_layout_params",
    "smart_horizontal_dx",
    "text_glyph_runs",
]
